fix missing lutris.util.amazon error reported:
  File "/usr/lib/python3.10/site-packages/lutris/services/amazon.py", line 20, in <module>
    from lutris.util.amazon.sds_proto2 import CompressionAlgorithm, HashAlgorithm, Manifest, ManifestHeader
ModuleNotFoundError: No module named 'lutris.util.amazon'