Fix call to sync_with_lutris()
Was running into this error...

```
service.sync_with_lutris()
TypeError: sync_with_lutris() missing 1 required positional argument: 'games'
```