Fix test discovery errors on systems with Gtk 4.0 installed
The issue is that most of the Gtk and Gdk imports in the Lutris code doesn't specify a Gnome version and therefore will use the default on the machine.
```
2026-01-24 23:17:54.262 [error] /mnt/DataDrive/workspace/lutris/lutris/gui/widgets/progress_box.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Pango

2026-01-24 23:17:54.348 [error] Unittest test discovery error for workspace:  /mnt/DataDrive/workspace/lutris
 Failed to import test module: runners.test_json
Traceback (most recent call last):
  File "/mnt/DataDrive/workspace/lutris/.venv/lib/python3.14/site-packages/gi/importer.py", line 137, in create_module
    introspection_module = get_introspection_module(namespace)
  File "/mnt/DataDrive/workspace/lutris/.venv/lib/python3.14/site-packages/gi/module.py", line 244, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/mnt/DataDrive/workspace/lutris/.venv/lib/python3.14/site-packages/gi/module.py", line 104, in __init__
    repository.require(namespace, version)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
```